Check env var
larscheid-schmitzhermes/keycloak-monitoring-prometheus pull request #1
Opened 2018-01-02 13:15 UTC by aidenkeating

Hi @tobilarscheid , would you mind taking a look?

Currently a change must be made to the configuration file in keycloak
to decide which directory the metrics data should be stored within.
An environment variable can be specified in the configuration, however
this still requires the configuration file to be modified.

This change will check an environment variable if no config value has
been provided. This allows the location of the metrics to be changed
without modifying any of the files within the original keycloak image.

Would this be something you'd be interested in including in the project?
I have found this quite useful as the work I have been doing made
modifying the keycloak configuration files a hassle.

2018-01-02 13:24 UTC, tobilarscheid requested changes
Thanks @aidenkeating, indeed a nice add on!
Can you remove the unrelated changes and consider my other comment? Looking forward to merge this! :-) :+1:

2018-01-02 13:24 UTC, tobilarscheid commented on README.md
> +- `keycloak_events_total` with labels
unrelated

2018-01-02 13:24 UTC, tobilarscheid commented on README.md
> +- `keycloak_admin_events_total` with labels
unrelated

2018-01-02 13:24 UTC, tobilarscheid commented on README.md
> +The naming scheme is compatible with [`prometheus-filesystem-exporter`](https://github.com/larscheid-schmitzhermes/prometheus-filesystem-exporter),
unrelated

2018-01-02 13:24 UTC, tobilarscheid commented on src/main/java/com/larscheidschmitzhermes/keycloak/events/MonitoringEventListenerProviderFactory.java
> +        String eventsDirectoryEnvVal = System.getenv(EVENTS_DIRECTORY_ENV);
can you move that inside the if block? so it's really only ever called as a fallback
also, maybe some debug logging might be nice here to help people figure out what they are doing

2018-01-02 15:06 UTC, aidenkeating commented
@tobilarscheid Thanks very much for the review 👍  I've made some changes. Would you mind taking another look when you have the time?

2018-01-02 15:49 UTC, tobilarscheid approved these changes
Very nice! I will merge and release tonight

2018-01-02 16:27 UTC, merged

2018-01-03 08:34 UTC, aidenkeating commented
Awesome, thanks! 😄